name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Command Line
      run: dotnet build -c Release ThreeDO.CommandLine\ThreeDO.CommandLine.csproj
    - name: Publish Command Line
      run: |
        dotnet publish -c Release -r win-x64 ThreeDO.CommandLine\ThreeDO.CommandLine.csproj
        dir ThreeDO.CommandLine\bin\Release\net7.0\win-x64\publish\
    - name: Build Windows UI
      run: dotnet build -c Release -f net7.0-windows10.0.19041.0 ThreeDO.UI\ThreeDO.csproj
    - name: Publish Windows UI
      #if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        dotnet publish -c Release -f net7.0-windows10.0.19041.0 /p:RuntimeIdentifierOverride=win10-x64 ThreeDO.UI\ThreeDO.csproj
        mkdir Output\ThreeDO
        xcopy /Y /E ThreeDO.UI\bin\Release\net7.0-windows10.0.19041.0\win10-x64\publish Output\ThreeDO
        powershell Compress-Archive -LiteralPath 'Output\ThreeDO' -DestinationPath ".\ThreeDO.zip"
    - name: Upload Windows UI
      uses: actions/upload-artifact@v2
      with:
        name: ThreeDO
        path: ThreeDO.zip
